### ISSUE TITLE
Async call

### ISSUE THREAD

**Issue by prcela** [qutheory/vapor-chat#2]
I am using this project and I don't know is it possible to make async call while the droplet is serving.

For example I want to send some important message to all users after some time delay. 
But this simple call wont print the message after time has passed:

```
   DispatchQueue.main.asyncAfter(deadline: .now()+5) {
        print("here we are")
    }
```

**Comment by tanner0101** [comment]
Try 

``` swift
return Response.async { portal in
    portal.close(with: "test")
}
```

**Comment by prcela** [comment]
It seems that blocks the main thread.

Semaphore waits on the current thread, I dont want to block main thread. 
Imagine this, it should be ok to serve the game clients while the game timed match is going, but when the game is finished, at some specific time I want to send that message to all clients.

**Comment by loganwright** [comment]
@prcela I believe this wasn't included in the snapshot of this project, but temporarily you could do:

```
try background {
    sleep(30)
    // do stuff 30 seconds later
}
```

We're still waiting on GM for Linux, but that will very likely also support GCD.

This should be perfectly fine as long as you have a reference to your websocket.

**Comment by prcela** [comment]
But how to call the function on main thread after that 30s from background thread block?

```
try background {
    sleep(30)
    // do stuff 30 seconds later
    MainThread.doSomeWork() // how to do this?
}
```

**Comment by loganwright** [comment]
@prcela Can you help me understand what you'd need the main thread for? I'm not sure if dispatch main works, but I'm not sure the value of it. On Vapor applications, the primary role of main is to accept and dispatch incoming connections. You probably don't want to do much execution on it so that it can route new connections as fast as possible.

**Comment by prcela** [comment]
Fair enough, but... I will give another good example for such need. 
Imagine virtual classroom where all students are writing exam that leasts exactly 40 min. Teacher will press "start exam" button which will activate that exam on server, server will send a ws message to all connected students to start the test. During the class the students are sending their finished tests to server via ws. After the 40 min the server should send the ws message that exam is over to all students in order to collect all written tests from connected students.

So, I need the main thread to send exam end message to all connected students.

**Comment by loganwright** [comment]
@prcela you'll need to store those somewhere in a way that you can access `studentsConnections: [WebSocket]`

Then notify all of them:

``` swift
try studentsConnections.forEach { ws in 
    try ws.send(yourMessage)
}
```
